### ISSUE TITLE
MISSING LEARN.MD FILE

### ISSUE THREAD

**Issue by Arshia-163** [Open-Source-Chandigarh/MeTube#21]
Learn.md file is missing in your  current repository.
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. 
So, Please assign this issue to me as a part of  hacktoberfest .

**Comment by MITARPALGROVER** [comment]
sure

**Comment by Arshia-163** [comment]
please check #25
