### ISSUE TITLE
In dark mode the Header of you MeTube is in white theme, and there is not any default component available to showcase videos in your projects

### ISSUE THREAD

**Issue by Harshcbx8** [Open-Source-Chandigarh/MeTube#22]
![Screenshot 2024-10-19 121851](https://github.com/user-attachments/assets/3ca21dc5-19f3-45c5-892e-a3af575662b0)
As I notices that in dark mode the header should be in also dark theme. 
Have some defalut layouts Sections where Videos have to stream in your webpage.

I will handle all these problem and fix issues will you assign that work to me!

**Comment by MITARPALGROVER** [comment]
okk!! i am assigning you this issue
