### ISSUE TITLE
Website Improvement - Addition of Footer

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/MeTube#24]
A footer is an essential part of a website, it helps in navigation and usability. Often contain important navigational links like "About Us," "Contact," "Privacy Policy," "Terms of Service," and "FAQ." This helps users find crucial information quickly, especially if they've scrolled to the bottom of a page.

Allow me to work on this issue, I'll create a responsive one!

![{C7718B99-6E7F-4465-9C81-E491BED87F22}](https://github.com/user-attachments/assets/222749e6-9bc3-43a6-b1a6-51ff67807683)

**Comment by MITARPALGROVER** [comment]
okk i am assigning you this issue

**Comment by BowlPulp** [comment]
Appreciated@

**Comment by AkshitBhandariCodes** [comment]
hey maintainer !
i can help you out with an responsive and nicely styled footer addition to your page 
kindly assign me this issue.

**Comment by BowlPulp** [comment]
I'll send a merge request within next few hours at max!

**Comment by BowlPulp** [comment]
Done! - https://github.com/Open-Source-Chandigarh/MeTube/pull/31#issue-2616270518
