### ISSUE TITLE
Adding Filter Options 

### ISSUE THREAD

**Issue by Arshia-163** [Open-Source-Chandigarh/MeTube#26]
We can add a filter in the main page by categories (e.g. sports, Entertainment,) which will allow users choose accordingly .
Please assign me this issue to me as a part of hacktoberfest .

**Comment by MITARPALGROVER** [comment]
can you please explain it what actually you will do like how will you make separate categories and how will these video display in those categories

**Comment by Arshia-163** [comment]
We will create filter buttons for different categories (e.g., "sports," "Entertainment") that users can click to display only videos related to that category. This helps users quickly find relevant content, improving navigation and efficiency.

**Comment by MITARPALGROVER** [comment]
okk you can work on this issue!!
i am assigning you this issue

**Comment by Arshia-163** [comment]
Please check #28
