### ISSUE TITLE
Addition of Meta Header Tags to boost seo

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/MeTube#32]
Currently the website doesn't have any of such tags, adding them would be beneficial for SEO optimization, and would allow users to get a glimpse of the website while sharing.
This is how it looks when you share the link right now - 
![{21AD4D47-4DB1-4810-B29A-D26A4BBA5641}](https://github.com/user-attachments/assets/e85ba524-e222-4803-b97e-11201e2f4f41)

(Notice it doesn't show any description, image, or any relevant information) This has to be fixed, kindly allow me to work on this!

**Comment by MITARPALGROVER** [comment]
okk i am assigning you this issue

**Comment by BowlPulp** [comment]
Done! - https://github.com/Open-Source-Chandigarh/MeTube/pull/33
