### ISSUE TITLE
Improvement in search functionality

### ISSUE THREAD

**Issue by ChauhanGauri** [Open-Source-Chandigarh/MeTube#9]
The search functionality on the webpage is currently configured such that the search operation can only be triggered by clicking the search button. Pressing the 'Enter' key after entering a query into the search input field does not initiate the search as expected. Implementing this functionality would enhance user experience by aligning with standard web practices, where pressing 'Enter' is commonly used to trigger search actions.
Kindly assign me this issue under Hacktober fest , if applicable.

**Comment by MITARPALGROVER** [comment]
Okk i am assigning you this
